import pygame

pygame.init()

localization = {
    "eng": {
        "vocab": ["apple", "crisp", "knife", "mouse", "print", "stone", "world"],
        "message": {
            "choose lang": "Choose your language:",
            "welcome": "Welcome to wordle!",
            "welcome2": "You have 5 attempt to guess the word.",
            "word request": "Enter your guess: ",
            "congrats": "Congratulations! You guessed the word!",
            "bad result": "Unfortunately, you lost...",
        },
        "keys": {
            pygame.K_a: "a",
            pygame.K_b: "b",
            pygame.K_c: "c",
            pygame.K_d: "d",
            pygame.K_e: "e",
            pygame.K_f: "f",
            pygame.K_g: "g",
            pygame.K_h: "h",
            pygame.K_i: "i",
            pygame.K_j: "j",
            pygame.K_k: "k",
            pygame.K_l: "l",
            pygame.K_m: "m",
            pygame.K_n: "n",
            pygame.K_o: "o",
            pygame.K_p: "p",
            pygame.K_q: "q",
            pygame.K_r: "r",
            pygame.K_s: "s",
            pygame.K_t: "t",
            pygame.K_u: "u",
            pygame.K_v: "v",
            pygame.K_w: "w",
            pygame.K_x: "x",
            pygame.K_y: "y",
            pygame.K_z: "z",
        },
    },
    "ru": {
        "vocab": ["печка", "лесок", "пульт", "рвота", "культ", "невод"],
        "message": {
            "welcome": "Добро пожаловать в wordle!",
            "welcome2": " У вас есть 5 попыток, чтобы угадать слово. ",
            "word request": "Введите ваше слово: ",
            "congrats": "Поздравляем! Вы угадали слово!",
            "bad result": "К сожалению, вы не угадали слово...",
        },
        "keys": {
            pygame.K_a: "ф",
            pygame.K_b: "и",
            pygame.K_c: "с",
            pygame.K_d: "в",
            pygame.K_e: "у",
            pygame.K_f: "а",
            pygame.K_g: "п",
            pygame.K_h: "р",
            pygame.K_i: "ш",
            pygame.K_j: "о",
            pygame.K_k: "л",
            pygame.K_l: "д",
            pygame.K_m: "ь",
            pygame.K_n: "т",
            pygame.K_o: "щ",
            pygame.K_p: "з ",
            pygame.K_q: "й",
            pygame.K_r: "к",
            pygame.K_s: "ы",
            pygame.K_t: "е",
            pygame.K_u: "г",
            pygame.K_v: "м",
            pygame.K_w: "ц",
            pygame.K_x: "ч",
            pygame.K_y: "н",
            pygame.K_z: "я",
            pygame.K_COMMA: "б",
            pygame.K_PERIOD: "ю",
            pygame.K_QUOTE: "э",
            pygame.K_SEMICOLON: "ж",
            pygame.K_RIGHTBRACKET: "ъ",
            pygame.K_LEFTBRACKET: "х",
            pygame.K_BACKQUOTE: "ё",
        },
    },
}
