# match row:
#     case 1:
#         match column:
#             case 1:
#                 screen.blit(get_mes(bukwa[0]), letter[0][0])
#             case 2:
#                 screen.blit(get_mes(bukwa[0]), letter[0][0])
#                 screen.blit(get_mes(bukwa[1]), letter[0][1])
#             case 3:
#                 screen.blit(get_mes(bukwa[0]), letter[0][0])
#                 screen.blit(get_mes(bukwa[1]), letter[0][1])
#                 screen.blit(get_mes(bukwa[2]), letter[0][2])
#             case 4:
#                 screen.blit(get_mes(bukwa[0]), letter[0][0])
#                 screen.blit(get_mes(bukwa[1]), letter[0][1])
#                 screen.blit(get_mes(bukwa[2]), letter[0][2])
#                 screen.blit(get_mes(bukwa[2]), letter[0][3])
#             case 5:
#                 screen.blit(get_mes(bukwa[0]), letter[0][0])
#                 screen.blit(get_mes(bukwa[1]), letter[0][1])
#                 screen.blit(get_mes(bukwa[2]), letter[0][2])
#                 screen.blit(get_mes(bukwa[3]), letter[0][3])
#                 screen.blit(get_mes(bukwa[4]), letter[0][4])
#     case 2:
#         match column:
#             case 1:
#                 screen.blit(get_mes(bukwa[5]), letter[1][0])
#             case 2:
#                 screen.blit(get_mes(bukwa[5]), letter[1][0])
#                 screen.blit(get_mes(bukwa[6]), letter[1][1])
#             case 3:
#                 screen.blit(get_mes(bukwa[5]), letter[1][0])
#                 screen.blit(get_mes(bukwa[6]), letter[1][1])
#                 screen.blit(get_mes(bukwa[7]), letter[1][2])
#             case 4:
#                 screen.blit(get_mes(bukwa[5]), letter[1][0])
#                 screen.blit(get_mes(bukwa[6]), letter[1][1])
#                 screen.blit(get_mes(bukwa[7]), letter[1][2])
#                 screen.blit(get_mes(bukwa[8]), letter[1][3])
#             case 5:
#                 screen.blit(get_mes(bukwa[5]), letter[1][0])
#                 screen.blit(get_mes(bukwa[6]), letter[1][1])
#                 screen.blit(get_mes(bukwa[7]), letter[1][2])
#                 screen.blit(get_mes(bukwa[8]), letter[1][3])
#                 screen.blit(get_mes(bukwa[9]), letter[1][4])
#     case 3:
#         match column:
#             case 1:
#                 screen.blit(get_mes(bukwa[10]), letter[2][0])
#             case 2:
#                 screen.blit(get_mes(bukwa[10]), letter[2][0])
#                 screen.blit(get_mes(bukwa[11]), letter[2][1])
#             case 3:
#                 screen.blit(get_mes(bukwa[10]), letter[2][0])
#                 screen.blit(get_mes(bukwa[11]), letter[2][1])
#                 screen.blit(get_mes(bukwa[12]), letter[2][2])
#             case 4:
#                 screen.blit(get_mes(bukwa[10]), letter[2][0])
#                 screen.blit(get_mes(bukwa[11]), letter[2][1])
#                 screen.blit(get_mes(bukwa[12]), letter[2][2])
#                 screen.blit(get_mes(bukwa[13]), letter[2][3])
#             case 5:
#                 screen.blit(get_mes(bukwa[10]), letter[2][0])
#                 screen.blit(get_mes(bukwa[11]), letter[2][1])
#                 screen.blit(get_mes(bukwa[12]), letter[2][2])
#                 screen.blit(get_mes(bukwa[13]), letter[2][3])
#                 screen.blit(get_mes(bukwa[14]), letter[2][4])
#     case 4:
#         match column:
#             case 1:
#                 screen.blit(get_mes(bukwa[15]), letter[3][0])
#             case 2:
#                 screen.blit(get_mes(bukwa[15]), letter[3][0])
#                 screen.blit(get_mes(bukwa[16]), letter[3][1])
#             case 3:
#                 screen.blit(get_mes(bukwa[15]), letter[3][0])
#                 screen.blit(get_mes(bukwa[16]), letter[3][1])
#                 screen.blit(get_mes(bukwa[17]), letter[3][2])
#             case 4:
#                 screen.blit(get_mes(bukwa[15]), letter[3][0])
#                 screen.blit(get_mes(bukwa[16]), letter[3][1])
#                 screen.blit(get_mes(bukwa[17]), letter[3][2])
#                 screen.blit(get_mes(bukwa[18]), letter[3][3])
#             case 5:
#                 screen.blit(get_mes(bukwa[15]), letter[3][0])
#                 screen.blit(get_mes(bukwa[16]), letter[3][1])
#                 screen.blit(get_mes(bukwa[17]), letter[3][2])
#                 screen.blit(get_mes(bukwa[18]), letter[3][3])
#                 screen.blit(get_mes(bukwa[19]), letter[3][4])
#     case 5:
#         match column:
#             case 1:
#                 screen.blit(get_mes(bukwa[20]), letter[4][0])
#             case 2:
#                 screen.blit(get_mes(bukwa[20]), letter[4][0])
#                 screen.blit(get_mes(bukwa[21]), letter[4][1])
#             case 3:
#                 screen.blit(get_mes(bukwa[20]), letter[4][0])
#                 screen.blit(get_mes(bukwa[21]), letter[4][1])
#                 screen.blit(get_mes(bukwa[22]), letter[4][2])
#             case 4:
#                 screen.blit(get_mes(bukwa[20]), letter[4][0])
#                 screen.blit(get_mes(bukwa[21]), letter[4][1])
#                 screen.blit(get_mes(bukwa[22]), letter[4][2])
#                 screen.blit(get_mes(bukwa[23]), letter[4][3])
#             case 5:
#                 screen.blit(get_mes(bukwa[20]), letter[4][0])
#                 screen.blit(get_mes(bukwa[21]), letter[4][1])
#                 screen.blit(get_mes(bukwa[22]), letter[4][2])
#                 screen.blit(get_mes(bukwa[23]), letter[4][3])
#                 screen.blit(get_mes(bukwa[24]), letter[4][4])
